<html>
<head>
    <title>To-do list app!</title>
    <link rel="stylesheet" href="./css/style.css">
    <script src="./js/deleteTodo.js" defer></script>

</head>

<h1>Nelly's to-do list</h1>
<div class="addTodo">
    <h2 id="test">Add a todo</h2>
    <form method="post">
        <input type="text" name="newTodo" formmethod="post" placeholder="Add a todo">
        <input type="submit" name="submit">
    </form>
</div>


<main>
        <div class="todo-board">
            <h3>To-dos</h3>
                <?php
                foreach($todos as $todo) {
                    echo "<div class='todo'>" . '<p>' . $todo['todo'] . '</p>' . "<button name='delete' class='btn-delete' data-id='" . $todo['id'] . "' " . "data-todo='" . $todo['todo'] . "'>Delete</button>" . '</div>';
                }
                ?>
        </div>

        <div class="done">
            <h3>Done</h3>
            <?php
                echo $newTodo;
            ?>
        </div>
    </main>
</html>