<html>
<head>
    <title>To-do list app!</title>
    <link rel="stylesheet" href="./css/style.css">

</head>

<h1>Nelly's to-do list</h1>
    <h2>Add a todo</h2>
    <form method="post">
        <input type="text" name="newTodo" formmethod="post" placeholder="Add a todo">
        <input type="submit" name="submit">
    </form>

<main>
        <div class="todo-board">
            <h3>To-dos</h3>
            <?php
            foreach($todos as $todo) {
                echo "<div class='todo'>" . $todo['id'] . ': ' . $todo['todo'] . '<br>' . '</div>';
            }
            ?>
        </div>

        <div class="done">
            <h3>Done</h3>
            <?php
                echo $newTodo;
            ?>
        </div>
    </main>
</html>