<html>
<head>
    <title>To-do list app!</title>
    <script src="./js/deleteTodo.js" defer></script>
    <script src="./js/completeTodo.js" defer></script>
    <link rel="stylesheet" href="./css/style.css">
    <link href="https://fonts.googleapis.com/css?family=The+Girl+Next+Door&display=swap" rel="stylesheet">
</head>

<h1>To-do list</h1>
<div class="addTodo">
    <h2 id="test">Add a todo</h2>
    <form method="post">
        <input type="text" name="newTodo" formmethod="post" placeholder="Add a todo">
        <input type="submit" class="btn-submit" name="submit">
    </form>
</div>


<main>
        <div class="todo-board">
            <h3>To-dos</h3>
                <?php
                    foreach($todos as $todo) {
                        echo "<div class='todo'>"
                            . "<p>" . $todo['todo'] . "</p>"
                            . "<button name='delete' class='btn-delete' data-id='" . $todo['id'] . "' "
                            . "data-todo='" . $todo['todo']
                            . "'>Delete</button>"
                            . "<button name = 'complete' class='btn-complete' data-id='" . $todo['id']
                            . "'>Completed</button>"
                            . '</div>';
                    }
                ?>
        </div>

        <div class="done">
            <h3>Done</h3>
            <?php
                foreach($completedTodos as $completedTodo) {
                    echo "<div class='todo'>"
                        . "<p>" . $completedTodo['todo'] . "</p>"
                        . "<button name='delete' class='btn-delete' data-id='" . $todo['id'] . "' "
                        . "data-todo='" . $todo['todo']
                        . "'>Delete</button>"
                        . "</div>";
                }
            ?>
        </div>
    </main>
</html>